### ISSUE TITLE
Logging for GET

### ISSUE THREAD

**Issue by Enshaedn** [ActoKids/api#15]
Log relevant information to CloudWatch

Estimated Time: 5 hours

**Comment by ZakBrinlee** [comment]
Actual Time: 4 hours

**NOTE:** Because I was only given 1 lambda function, I was only able to do 1 GET request into the AD 440 AWS school account. I did do the other GET request on my personal AWS account and included the code in my pull-request. 

GET all events (school AWS account):
`curl -v https://91i4hx5677.execute-api.us-east-2.amazonaws.com/Sprint3/v1/events`

GET event by id (personal AWS account):
`curl -v https://8cex032b53.execute-api.us-west-2.amazonaws.com/sprint2_test/v1/events/1`

Log relevant information to CloudWatch for GET functions. 
* log start and end of lambda function
* log event_id parameter for GET event by id call  
* log in try catch for error, success and event not found
* console.error() for errors
* console.log() for non-errors

[Branch](https://github.com/ActoKids/api/tree/feature/ZakIssue%2315GETLogs)
[Pull-Request](https://github.com/ActoKids/api/pull/32)
[Wiki](https://github.com/ActoKids/api/wiki/Logging-for-GET-requests)

**I reviewed the following pull requests**:
[Travis Tackett #30](https://github.com/ActoKids/api/pull/30) - I reviewed the pull request and approved it. On a later inspection, I noticed that the code has the variables and table key as eventID. This does not match the data model. I informed Travis of my mistake and created a bug. We are looking into how to correct the issue/pull-request. 
[Bug issue created](https://github.com/ActoKids/api/issues/31)

[Alex Clontz #28](https://github.com/ActoKids/api/pull/28) - I reviewed Alex's code. All worked well and matched the data model and good commenting. 

[Zach Daniels #29](https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/29) - NOT A PULL REQUEST - I worked with Zach to get a Web UI login built to sign in users and get the tokens. Tested the Cognito with PostMan using the required tokens/id and it works as expected. 

**Note:** Because Travis and Alex's Lambda functions do not belong to me, I did not test the code in Lambda Management Console to review the CloudWatch Logs as I was able to do with mine. See steps in [Wiki](https://github.com/ActoKids/api/wiki/Logging-for-GET-requests) for how to view CloudWatch Logs from Lambda without CloudWatch permissions. 

**Notes:**
* The v1/events/{id} GET request will need to have the handling for PUT and DELETE requests during later sprints. 

GET all events log:
![ak-api-zak-lambda_cloudwatchlogs](https://user-images.githubusercontent.com/22527777/53077021-f5d2ec80-34a5-11e9-823f-1a6baf30d580.PNG)

GET event by id success log:
![geteventsbyid_cloudwatch_success_log](https://user-images.githubusercontent.com/22527777/53074351-61fe2200-349f-11e9-8d2d-c9f5cf0892bf.PNG)
