### ISSUE TITLE
Create custom domain

### ISSUE THREAD

**Issue by Enshaedn** [ActoKids/api#20]
Create a custom domain - api.example.com for Toddy's website & issue certificate for it.

**Comment by MrSamsa42** [comment]
Estimated time: ~3 hours
Actual time: 3 hours (spread out over several days)

Updated wiki: https://github.com/ActoKids/api/wiki/API-accessability-via-HTTPS-custom-domain
Note:  The wiki describes how to set up an "edge-optimized" or "regional" API and custom domain endpoint.  The deployed code is a "regional" API and endpoint.  

Deployed code: https://api.2edusite.com/v1/ping

Testing:
Since the "ping" is only supposed to demonstrate successful communication, a request from any route will return the same basic response. I updated the Lambda function to return the request type in the response object, then tested using the following curl commands:

curl -sb -H "Content-Type:application/JSON" -X GET https://api.2edusite.com/v1/ping
response:
{"pingMessage":"API is working","todaysDate":"2019-02-20T23:30:17.331Z","requestType":"GET"}

curl -sb -H "Content-Type:application/JSON" -X POST -d '{}' https://api.2edusite.com/v1/ping
response:
{"pingMessage":"API is working","todaysDate":"2019-02-20T23:30:55.571Z","requestType":"POST"}

curl -sb -H "Content-Type:application/JSON" -X PUT -d '{}' https://api.2edusite.com/v1/ping
response:
{"pingMessage":"API is working","todaysDate":"2019-02-20T23:31:46.112Z","requestType":"PUT"}

curl -sb -H "Content-Type:application/JSON" -X DELETE -d '{}' https://api.2edusite.com/v1/ping
response:
{"pingMessage":"API is working","todaysDate":"2019-02-20T23:32:05.493Z","requestType":"DELETE"}

I reviewed the following PRs:
https://github.com/ActoKids/api/pull/32#pullrequestreview-206044249
https://github.com/ActoKids/api/pull/33#pullrequestreview-205992375





link to PR for updated Lambda function: https://github.com/ActoKids/api/pull/34
