### ISSUE TITLE
Configure API Gateway 1Box endpoints

### ISSUE THREAD

**Issue by ZakBrinlee** [ActoKids/api#39]
Configure API Gateway with domains and SSL for all endpoints for the 1Box environment. 

- Need to work with a teammate from the DevOps for this task
- What did you do on Route 53?
- What did you do on API Gateway?
- What did you do on Certificate Manager?
- List endpoint(s) created

Endpoint: api-[firstnamelastinitial].2edusite.com
Region: Ohio if regional / N. Virginia if edge

Estimated Time: 2 hours

**Comment by Enshaedn** [comment]
I worked with Lyndon to complete this task.

Within Certificate Manager I was able to request 1 certificate for all of the custom domain names required for the teams 1box environment. However, I did not have permissions to validate ownership of the domains so Lyndon had to validate them.

Once the certificates were issued I was able to go to API Gateway (us-east-2) and set custom domain names. I went with the regional setting since I had also requested the certificates in us-east-2. I created one custom domain per team member, each custom domain using the same certificate. 

Once the custom domain names were created I sent all of their respective target domain names paired with the custom domain itself to Lyndon to create ALIAS records in Route 53 via a [DevOps Issue](https://github.com/ActoKids/devops/issues/26). I didn't do anything in Route 53 as our team does not have any permissions there. 
![image](https://user-images.githubusercontent.com/23545971/53301945-952d1200-380d-11e9-9403-02a1a6604fa1.png)


I created endpoints for each team member:
- api-alexc.2edusite.com/v1/events
- api-jona.2edusite.com/v1/ping
- api-zakb.2edusite.com/v1/v1/events
- api-zachd.2edusite.com
- api-travist.2edusite.com/v1/events/{eventID}
- api-karenp.2edusite.com

I was able to verify that my, Jon's, and Zak's custom domains were working. In order to set a base path for the custom domain an API needs to exist so I only set /v1 paths for mine, Jon's, Zak's, and Travis' APIs. Zach and Karen do not have any APIs yet created in API Gateway.

Example of working custom domain:
![image](https://user-images.githubusercontent.com/23545971/53301954-b42ba400-380d-11e9-80cb-391bbe63493b.png)

Estimated Time: 2 hours
Total Time: 2 hours

**Comment by Enshaedn** [comment]
Removed DevOps as they have their own [issue](https://github.com/ActoKids/devops/issues/30) which @Stakada is working on.

**Comment by T-travis** [comment]
I tested these with https://
- api-alexc.2edusite.com/v1/events
- api-jona.2edusite.com/v1/ping
- api-zakb.2edusite.com/v1/v1/events
- api-travist.2edusite.com/v1/events/{eventID}
- api-zachd.2edusite.com
- api-karenp.2edusite.com

They all work as expected.  Note: the last two should not work and - api-travist.2edusite.com/v1/events/{eventID} must be used in curl.  Nice work Alex

**Comment by Enshaedn** [comment]
## Accomplished
Successfully created custom domain names for each API team member (all require https://):
- api-alexc.2edusite.com
- api-jona.2edusite.com
- api-zakb.2edusite.com
- api-travist.2edusite.com
- api-zachd.2edusite.com
- api-karenp.2edusite.com

Currently Zach and Karen's custom domains don't have a base path or point to an API as they haven't created any yet. The other four have valid endpoints - documented in the Testing section below.

### Steps Taken:
- First I created a single certificate for every custom domain name going to be used.
- Next Lyndon assisted by confirming the certificates via DNS confirmation in Route 53. 
![image](https://user-images.githubusercontent.com/23545971/53748637-95a35980-3e5a-11e9-8812-9aafbbca83cf.png)
- Once the certificate was issued I was able to make each custom domain name object in API Gateway and apply base paths/APIs where applicable.
![image](https://user-images.githubusercontent.com/23545971/53748766-ddc27c00-3e5a-11e9-8356-e5b400568483.png)
- The last step involved providing Lyndon with the Target Domain Name for each custom domain name object created so that he could create aliases in Route 53 for each of them. 

## Sprint 4 Details
- Pull Request (None for this sprint; no coding done)
- [Wiki](https://github.com/ActoKids/api/wiki/Configure-API-Gateway-1box-Endpoints)
- Deployed Code (None for this sprint; no coding done)

Time estimated: 2 hours
Actual time: 2 hours

## Testing
### Currently valid and verified endpoints:
- [https://api-alexc.2edusite.com/v1/events](https://api-alexc.2edusite.com/v1/events)
![image](https://user-images.githubusercontent.com/23545971/53749166-af916c00-3e5b-11e9-8fc0-eba6f281ad3b.png)
- [https://api-jona.2edusite.com/v1/events/eventsFilter?approver=Zeus](https://api-jona.2edusite.com/v1/events/eventsFilter?approver=Zeus)
![image](https://user-images.githubusercontent.com/23545971/53749277-e5365500-3e5b-11e9-9c6d-ec693df9cffb.png)
- [https://api-zakb.2edusite.com/v1/v1/events](https://api-zakb.2edusite.com/v1/v1/events) - Note: endpoint has been fixed. See [issue 47.](https://github.com/ActoKids/api/issues/47)
![image](https://user-images.githubusercontent.com/23545971/53749344-07c86e00-3e5c-11e9-9630-6f6c2475e575.png)
- api-travist.2edusite.com/v1/events/{event_id}
- Note: Travis' endpoint does work via curl (prefix https://), but not in a browser address bar. Probably because it is a DELETE operation and not GET.
![image](https://user-images.githubusercontent.com/23545971/53749699-cbe1d880-3e5c-11e9-8ca0-7cefc08e92a1.png)

### Valid, not verified:
- Karen & Zach don't have APIs created yet so their custom domain names don't point to anything currently. As soon as they have an API created and applied to the custom domain names it should work since everything else is set up.

## Tested
- Travis' [issue](https://github.com/ActoKids/api/issues/37)
- Jon's [pull request](https://github.com/ActoKids/api/pull/45)
- Zak's [issue](https://github.com/ActoKids/api/issues/38)
- Zak's [bug fix](https://github.com/ActoKids/api/issues/47)
- Travis' [pull request](https://github.com/ActoKids/api/pull/48)

## Bugs / Issues
- DevOps: [CloudWatch Access](https://github.com/ActoKids/devops/issues/23)
- DevOps: [Dynamo Fix](https://github.com/ActoKids/devops/issues/21)
- DevOps: [Route 53 Help](https://github.com/ActoKids/devops/issues/26)
- DevOps: [TravisCI Issue](https://github.com/ActoKids/devops/issues/37)
- API: [Enhanced comments/logging](https://github.com/ActoKids/api/issues/46)

**Comment by ZakBrinlee** [comment]
**Review by Zak Brinlee:**
1Box endpoints are configured. I was able to clearly follow Alex's Issue progress and his Wiki. 

**Testing:**
I tested the following endpoints:
 - api-alexc.2edusite.com/v1/events
 - api-jona.2edusite.com/v1/ping
 - api-zakb.2edusite.com/v1/v1/events
 - api-travist.2edusite.com/v1/events/{eventID}

**Notes:**
As Alex has already pointed out, api-travist.2edusite.com/v1/events/{eventID} endpoint does not work on the browser but with curl. 

Everything else provided correct responses. All looks really good and clear to follow. Well done.
I can't find any issues or bugs that Alex hasn't already addressed.

**Comment by MrSamsa42** [comment]
I checked API gateway and confirmed that all of the endpoints were created and associated with the same ACM certificate, and I reviewed the wiki.  Everything looks good.  

I used curl to test the following endpoints:
https://api-alexc.2edusite.com/v1/events
https://api-jona.2edusite.com/v1/ping
![image](https://user-images.githubusercontent.com/27866709/53757249-0b65f000-3e70-11e9-861d-98aae8159db1.png)

...and
https://api-zakb.2edusite.com/v1/v1/events
(See[ Issue 47](https://github.com/ActoKids/api/issues/47))
![image](https://user-images.githubusercontent.com/27866709/53757298-2df80900-3e70-11e9-83ae-12ef306faf3b.png)

...and
https://api-travist.2edusite.com/v1/events/{eventID}
![image](https://user-images.githubusercontent.com/27866709/53757798-78c65080-3e71-11e9-8e76-e5e68dd01956.png)
(checked Dynamo to verify that specified item was removed)

As noted above, the following endpoints do not have APIs attached, and so could not be tested:
https://api-karenp.2edusite.com
https://api-zachd.2edusite.com
See [Issue 54](https://github.com/ActoKids/api/issues/44).
