### ISSUE TITLE
Logging and Dashboard for API team

### ISSUE THREAD

**Issue by ZakBrinlee** [ActoKids/api#41]
Standardize the logging and create a dashboard in CloudWatch for user-friendly monitoring. 

Estimated Time: 6 hrs

**Comment by Enshaedn** [comment]
I opened an [issue](https://github.com/ActoKids/devops/issues/23) to get access to CloudWatch a week ago. Last I checked (yesterday) it still hadn't been fixed. 

I was provided a policy screen shot showing that we do have restrictions for CloudWatch.
![image](https://user-images.githubusercontent.com/23545971/53536597-d5192100-3abb-11e9-94e4-069f97c08cb7.png)

**Comment by zach-daniels** [comment]
Estimated time : 6 hrs
Total time : 2 hrs

Turns out I overestimated the complexity of this task. I created a Dashboard for the Lambda functions the API is using. I recall you wanting the Prod and Dev environments monitored, but at this moment, the functions have not been moved to those environments yet. The dashboard has 4 widgets tracking each Lambda metric: # of errors, avg duration of function, # of times the function was invoked, and # of times the function was throttled. 

https://github.com/ActoKids/api/wiki/Cloudwatch-Dashboard

Logging Standards

-The function has started ('Starting '____' function')
-Any and all parameters ex (Path, eventId, etc)	
-Which route is being hit (Hit '____' route)
-Log results of try/catches
	-Note what's happening in success, note error in a catch
-Function ending ("'____' function ended")

**Comment by ZakBrinlee** [comment]
Review by Zak Brinlee:
I was able to clearly follow Zach's Wiki and his Dashboard.

Testing:

- Went to AD 440 - Ohio Region - CloudWatch
- Selected Dashboards
- Selected api-lambda-dashboard
- Reviewed the 4 widgets

Notes:
Very easy to follow the dashboard. Looks awesome

**Comment by T-travis** [comment]
I went to CloudWatch then selected Dashboard then api-lambda-dashboard and behold a dashboard of widgets.  I looks like it works correctly. See image below:

![image](https://user-images.githubusercontent.com/25231407/53926104-20d94680-4037-11e9-90b6-b9bbe5ec29e8.png)

**Comment by MrSamsa42** [comment]
I went to Cloud Watch and monitored the Invocations chart as I made multiple requests to my own lambda.  Upon refreshing, the chart responded as expected.
