### ISSUE TITLE
redundant base path mapping on api-zakb.2edusite.com

### ISSUE THREAD

**Issue by MrSamsa42** [ActoKids/api#47]
There is a /v1 base path mapping on api-zakb.2edusite.com, but the associated API already has its /events resource nested inside a resource named "/v1".  As a result, the effective path to the events resource is v1/v1/events.

Expected behavior:
Path to events is https://api-zakb.2edusite.com/v1/events

Actual behavior:
Path to events is https://api-zakb.2edusite.com/v1/v1/events

**Comment by ZakBrinlee** [comment]
**Issue**:
- For Sprint3, my function was separate from the custom domain. In order to follow the Swagger I put the 'v1' path into my API Gateway stage. When Alex created the Custom Domain he set the base path mapping to 'v1' as well. 

**Solution**:
- Created a new stage for the custom domain base path mapping to connect to. 
- Sprint4 API Gateway stage is created without a 'v1' resource path. 
- **Contacted Alex** for his review and help for resolve with the custom domain base path. 
- See screenshot of change below
<img width="1178" alt="bugissuesolution" src="https://user-images.githubusercontent.com/22527777/53764672-c5feee00-3e82-11e9-8b00-d322cd4caee4.PNG">

**Testing**: 
- After Alex made his changes, I tested the endpoint for the correct path and results. 
- Endpoint: **[https://api-zakb.2edusite.com/v1/events](https://api-zakb.2edusite.com/v1/events)**

**Comment by Enshaedn** [comment]
Zak fixed the issue with his API and deployed a new stage. I updated the stage value in the custom domain name base path mapping and then tested the endpoint. It is now working as desired.

![image](https://user-images.githubusercontent.com/23545971/53764496-52f57780-3e82-11e9-837b-55c49a4a696c.png)
