### ISSUE TITLE
Fix the POST Lambda function

### ISSUE THREAD

**Issue by ZakBrinlee** [ActoKids/api#55]
Fix the POST Lambda file naming conventions and file structure to be able to work with Travis CI and able to be published to the Production environment. 

Expected Time: 2 hours

Actual Time:

**Comment by Enshaedn** [comment]
The [pull request](https://github.com/ActoKids/api/pull/59) fixes the file structure and variables within the function to work completely within the prod environment.

**Comment by Enshaedn** [comment]
## Accomplished:
I helped create and fix the file structure for our repository. I adjusted the necessary variables within the Lambda function for deployment to the production environment to work via TravisCI. To ensure that everything is working as intended, and so that the UI team could test in the production region, I updated the production Lambda with the new code as well. 

Note: There were also minor updates to the data model and swagger - all in the same PR.

## Sprint 5 Details:
- [Pull Request](https://github.com/ActoKids/api/pull/59)
- [Wiki](https://github.com/ActoKids/api/wiki/POST-Request-For-Events)
- [Deployed Code](https://github.com/ActoKids/api/blob/dev/lambda/events/post/index.js)

Estimated Time: 2 hours
Actual Time: 2 hours

## Testing
Create new event in prod region:
![image](https://user-images.githubusercontent.com/23545971/54495790-6e11af80-48a4-11e9-8cb7-43c660900c7f.png)

New event is returned from prod region:
![image](https://user-images.githubusercontent.com/23545971/54495805-91d4f580-48a4-11e9-90a4-effa5b8f2b83.png)

New event returned from GET by event_id:
![image](https://user-images.githubusercontent.com/23545971/54495884-a796ea80-48a5-11e9-8b7b-afb1b854fbd8.png)

### Tested
- [Travis' PR](https://github.com/ActoKids/api/pull/60)
- [Travis' PR](https://github.com/ActoKids/api/pull/61)
- [Zak's PR](https://github.com/ActoKids/api/pull/63)
- [Zach's PR](https://github.com/ActoKids/api/pull/68)

### Bugs / Issues
- UI Bug Reported: [Access-Control-Allow-Origin](https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/107)
- DevOps: [Prod DynamoDB Table Creation](https://github.com/ActoKids/devops/issues/55)
- DevOps: [TravisCI](https://github.com/ActoKids/devops/issues/37)
